apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ingress-eximpedia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      namespace: ingress-eximpedia
      labels:
        app: backend-app
    spec:
      containers:
      - name: backenddockerrepo
        image: acreximpediacidev.azurecr.io/backend:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 4300
      restartPolicy: Always
     
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-svc
  namespace: ingress-eximpedia
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 4300
      targetPort: 4300



      
